apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.12.1
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: monitoring-stack
spec:
  ports:
  - port: 5601
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: kibana