kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: godblessyou-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
- role: worker
- role: worker 