apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/app

namespace: staging

commonLabels:
  environment: staging

patches: []  # 必要に応じてパッチを追加

configMapGenerator: []  # 必要に応じてConfigMapを生成

secretGenerator: []  # 必要に応じてSecretを生成 