apiVersion: apps/v1
kind: Deployment
metadata:
  name: godblessyou
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbc-product
  template:
    metadata:
      labels:
        app: gbc-product
    spec:
      containers:
      - name: godblessyou
        image: godblessyou:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: postgresql://godblessyou:change-me-in-production@postgresql:5432/godblessyou
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 