apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbc-product
spec:
  selector:
    matchLabels:
      app: gbc-product
  replicas: 1
  template:
    metadata:
      labels:
        app: gbc-product
    spec:
      containers:
      - name: gbc-product
        image: node:20-slim  # 開発初期段階なのでNode.jsベースイメージを使用
        command: ["node"]
        args: ["-e", "require('http').createServer((req, res) => { res.writeHead(200); res.end('Hello from GBC Product!'); }).listen(8000);"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10 