apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: godblessyou-dev
resources:
- ../../base

commonLabels:
  environment: development

configMapGenerator:
- name: godblessyou-config
  literals:
  - NODE_ENV=development

secretGenerator:
- name: godblessyou-secrets
  literals:
  - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/godblessyou_dev

patches:
- target:
    kind: Deployment
    name: godblessyou-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: godblessyou-app:dev 