apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: godblessyou-dev

resources:
  - ../../base

configMapGenerator:
  - name: frontend-config
    literals:
      - NODE_ENV=development
      - API_URL=http://backend.godblessyou-dev.svc.cluster.local
  - name: backend-config
    literals:
      - NODE_ENV=development
  - name: postgres-config
    literals:
      - POSTGRES_DB=godblessyou

secretGenerator:
  - name: backend-secrets
    literals:
      - DATABASE_URL=postgresql://godblessyou:godblessyou@postgres.godblessyou-dev.svc.cluster.local:5432/godblessyou
      - JWT_SECRET=development-jwt-secret
  - name: postgres-secrets
    literals:
      - POSTGRES_USER=godblessyou
      - POSTGRES_PASSWORD=godblessyou

patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: localhost:5000/godblessyou-frontend:dev
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: localhost:5000/godblessyou-backend:dev 