apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: godblessyou-prod
resources:
- ../../base

commonLabels:
  environment: production

configMapGenerator:
- name: godblessyou-config
  literals:
  - NODE_ENV=production

secretGenerator:
- name: godblessyou-secrets
  literals:
  - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/godblessyou_prod

patches:
- target:
    kind: Deployment
    name: godblessyou-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: godblessyou-app:prod
    - op: replace
      path: /spec/replicas
      value: 3 