apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: godblessyou-prod
resources:
- ../../base

commonLabels:
  environment: production

configMapGenerator:
- literals:
  - NODE_ENV=production
  name: godblessyou-config

secretGenerator:
- literals:
  - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/godblessyou_prod
  name: godblessyou-secrets

patches:
- patch: "- op: replace\n  path: /spec/template/spec/containers/0/image\n  value:
    godblessyou-app:prod\n- op: replace\n  path: /spec/replicas\n  value: 3 "
  target:
    kind: Deployment
    name: godblessyou-app
images:
- name: ghcr.io/n18011/godblessyou/app
  newTag: 03cbb690e55ffcb964f3ca440dd1cd0c8b2da82f
